### ISSUE TITLE
Overriding original function

### ISSUE THREAD

**Issue by lokhman** [alangpierce/go-forceexport#2]
Hi! Thank you for suggesting this approach of accessing unexported functions.

I was playing with your library and thought would it be possible to override the original function with own implementation, e.g. to define `func myTimeNow() (int64, int32) { ... }` and make calling `time.Now()` to execute `myTimeNow` function instead.

**Comment by alangpierce** [comment]
Hmm, good question. TBH I haven't used Go in a while (this project is from two years ago), but my impression is that code like `time.Now()` compiles to a direct call to a function in the code segment (read-only memory), so there's no opportunity to modify its behavior. This project (accessing an arbitrary function) is an easier problem since it's more just a matter of finding the right pointer and then finding a way to call that function from Go.

If your goal is to stub out time for tests, I imagine the best approach is to make all calls through some indirection that you introduce, like your own interface/wrapper, so you can modify it for tests.

**Comment by skipor** [comment]
Seems [github.com/bouk/monkey](https://github.com/bouk/monkey)  can replace original functions and methods.

**Comment by lokhman** [comment]
@alangpierce You were right regarding read-only memory, however as @skipor mentioned, monkey patching library can hack it. Very interesting approach! I was missing getting access part for writing into memory. Thank you both for help!
